### ISSUE TITLE
Bandit 1.6.2 doesn't honor excluded directories

### ISSUE THREAD

**Issue by anapaulagomes** [FussyFox/bandit#19]
See https://github.com/PyCQA/bandit/issues/488.

**Comment by anapaulagomes** [comment]
I've tested with 1.5.0 and it works. Can we pin bandit version to 1.5.0?

**Comment by codingjoe** [comment]
@anapaulagomes I've seen  this too. There are soo many problems with version 1.6 :/
Go for it !
